/**
 * generateDefaultMovies.js
 *
 * Run this once from your project root to build the default movie seed list.
 * It searches TMDB for each title and saves results to src/data/defaultMovies.json
 *
 * Usage:
 *   node scripts/generateDefaultMovies.js
 *
 * Requires EXPO_PUBLIC_TMDB_API_KEY in your .env file.
 * Takes ~2-3 minutes to run (rate limiting delay between requests).
 */

require("dotenv").config();
const fs = require("fs");
const path = require("path");

const API_KEY = process.env.EXPO_PUBLIC_TMDB_API_KEY;
if (!API_KEY) {
  console.error("ERROR: EXPO_PUBLIC_TMDB_API_KEY not found in .env");
  process.exit(1);
}

const DELAY_MS = 260; // Stay under TMDB rate limit

const MOVIE_TITLES = [
  // --- Original 250 ---
  "300",
  "2012",
  "12 Angry Men",
  "2001: A Space Odyssey",
  "21 Jump Street",
  "22 Jump Street",
  "3 Idiots",
  "A Nightmare on Elm Street",
  "A Quiet Place",
  "Airplane!",
  "Aladdin",
  "Alien",
  "Aliens",
  "Amélie",
  "American Beauty",
  "American History X",
  "American Pie",
  "Anchorman: The Legend of Ron Burgundy",
  "Apocalypse Now",
  "Armageddon",
  "Avatar",
  "Back to the Future",
  "Bad Boys",
  "Bambi",
  "Basic Instinct",
  "Beauty and the Beast",
  "Ben-Hur",
  "Black Panther",
  "Blade Runner",
  "Bohemian Rhapsody",
  "Boogie Nights",
  "Borat",
  "Brave",
  "Bridesmaids",
  "Captain America: The First Avenger",
  "Cars",
  "Casablanca",
  "Casino",
  "Casino Royale",
  "Cinderella",
  "Cinema Paradiso",
  "Citizen Kane",
  "City of God",
  "Clerks",
  "Coco",
  "Con Air",
  "Crouching Tiger, Hidden Dragon",
  "Deadpool",
  "Despicable Me",
  "Die Hard",
  "Dilwale Dulhania Le Jayenge",
  "Divergent",
  "Django Unchained",
  "Double Indemnity",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "Due Date",
  "Dumb and Dumber",
  "E.T. the Extra-Terrestrial",
  "Elf",
  "Face/Off",
  "Falling Down",
  "Fargo",
  "Ferris Bueller's Day Off",
  "Fight Club",
  "Finding Nemo",
  "Forrest Gump",
  "Frozen",
  "Frozen II",
  "Full Metal Jacket",
  "Get Out",
  "Ghostbusters",
  "Gladiator",
  "Goldfinger",
  "Gone with the Wind",
  "Goodfellas",
  "Grave of the Fireflies",
  "Gravity",
  "Groundhog Day",
  "Guardians of the Galaxy",
  "Halloween",
  "Harry Potter and the Philosopher's Stone",
  "Heat",
  "Home Alone",
  "How to Train Your Dragon",
  "Ice Age",
  "Inception",
  "Independence Day",
  "Indiana Jones and the Last Crusade",
  "Indiana Jones and the Temple of Doom",
  "Inside Out",
  "Insidious",
  "Interstellar",
  "Iron Man",
  "It",
  "It's a Wonderful Life",
  "Jaws",
  "Jerry Maguire",
  "John Wick",
  "Joker",
  "Juno",
  "Jurassic Park",
  "Knocked Up",
  "Kung Fu Panda",
  "La La Land",
  "Lawrence of Arabia",
  "Léon: The Professional",
  "Lethal Weapon",
  "Lethal Weapon 2",
  "Life Is Beautiful",
  "Mad Max: Fury Road",
  "Mean Girls",
  "Memento",
  "Minions",
  "Mission: Impossible",
  "Moana",
  "Modern Times",
  "Monsters, Inc.",
  "Mughal-e-Azam",
  "Mulan",
  "Napoleon Dynamite",
  "National Treasure",
  "Natural Born Killers",
  "North by Northwest",
  "Old School",
  "Oldboy",
  "Once Upon a Time in the West",
  "Parasite",
  "Peter Pan",
  "Pinocchio",
  "Pirates of the Caribbean: At World's End",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Pirates of the Caribbean: Dead Men Tell No Tales",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Platoon",
  "Predator",
  "Psycho",
  "Pulp Fiction",
  "Raiders of the Lost Ark",
  "Ratatouille",
  "Rear Window",
  "Reservoir Dogs",
  "RoboCop",
  "Rocky",
  "Saving Private Ryan",
  "Scarface",
  "Schindler's List",
  "School of Rock",
  "Se7en",
  "Seven Samurai",
  "Sholay",
  "Shrek",
  "Shrek 2",
  "Sing",
  "Singin' in the Rain",
  "Skyfall",
  "Sleeping Beauty",
  "Slumdog Millionaire",
  "Snow White and the Seven Dwarfs",
  "Some Like It Hot",
  "Spider-Man",
  "Spirited Away",
  "Star Wars",
  "Step Brothers",
  "Sunset Boulevard",
  "Superbad",
  "Tangled",
  "Ted",
  "Terminator 2: Judgment Day",
  "The 40-Year-Old Virgin",
  "The Avengers",
  "Avengers: Endgame",
  "The Big Lebowski",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Conjuring",
  "The Dark Knight",
  "The Day After Tomorrow",
  "The Departed",
  "The Exorcist",
  "The Fault in Our Stars",
  "The Godfather",
  "The Godfather Part II",
  "The Good, the Bad and the Ugly",
  "The Grand Budapest Hotel",
  "The Great Dictator",
  "The Green Mile",
  "The Grinch",
  "The Hangover",
  "The Hunger Games",
  "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay Part 1",
  "The Hunger Games: Mockingjay Part 2",
  "The Hurt Locker",
  "The Incredibles",
  "The Intouchables",
  "The Jungle Book",
  "The Karate Kid",
  "The King's Speech",
  "The Lego Movie",
  "The Lion King",
  "The Little Mermaid",
  "The Lives of Others",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Return of the King",
  "The Lord of the Rings: The Two Towers",
  "The Matrix",
  "The Notebook",
  "The Parent Trap",
  "The Pianist",
  "The Polar Express",
  "The Prestige",
  "The Princess Bride",
  "The Revenant",
  "The Ring",
  "The Rock",
  "The Sandlot",
  "The Secret Life of Pets",
  "The Shawshank Redemption",
  "The Shining",
  "The Silence of the Lambs",
  "The Sixth Sense",
  "The Social Network",
  "The Sound of Music",
  "The SpongeBob SquarePants Movie",
  "The Super Mario Bros. Movie",
  "The Ten Commandments",
  "The Terminator",
  "The Truman Show",
  "The Twilight Saga: Eclipse",
  "The Twilight Saga: New Moon",
  "The Usual Suspects",
  "The Wizard of Oz",
  "The Wolf of Wall Street",
  "Thor",
  "Titanic",
  "Toy Story",
  "Training Day",
  "Transformers",
  "Transformers: Revenge of the Fallen",
  "True Romance",
  "Twilight",
  "Unforgiven",
  "Up",
  "Vertigo",
  "WALL-E",
  "We're the Millers",
  "Wedding Crashers",
  "Whiplash",
  "Witness for the Prosecution",
  "World War Z",
  "Zootopia",

  // --- Added 250 ---
  "On the Waterfront",
  "All About Eve",
  "A Streetcar Named Desire",
  "The Bridge on the River Kwai",
  "Spartacus",
  "To Kill a Mockingbird",
  "Butch Cassidy and the Sundance Kid",
  "The Graduate",
  "Bonnie and Clyde",
  "West Side Story",
  "Breakfast at Tiffany's",
  "The Philadelphia Story",
  "Monty Python and the Holy Grail",
  "Bicycle Thieves",
  "Rashomon",
  "Grand Illusion",
  "8½",
  "Chinatown",
  "One Flew Over the Cuckoo's Nest",
  "Taxi Driver",
  "Annie Hall",
  "The Empire Strikes Back",
  "Return of the Jedi",
  "Close Encounters of the Third Kind",
  "Network",
  "The Deer Hunter",
  "Grease",
  "Saturday Night Fever",
  "Blazing Saddles",
  "Young Frankenstein",
  "Kramer vs. Kramer",
  "All the President's Men",
  "Dog Day Afternoon",
  "The French Connection",
  "A Clockwork Orange",
  "American Graffiti",
  "Top Gun",
  "Beverly Hills Cop",
  "Trading Places",
  "Coming to America",
  "Rain Man",
  "Good Morning Vietnam",
  "Wall Street",
  "The Color Purple",
  "Sixteen Candles",
  "The Breakfast Club",
  "Dirty Dancing",
  "Stand By Me",
  "A Fish Called Wanda",
  "Field of Dreams",
  "When Harry Met Sally",
  "Beetlejuice",
  "Big",
  "Who Framed Roger Rabbit",
  "Gremlins",
  "The Thing",
  "Poltergeist",
  "Tootsie",
  "Risky Business",
  "Pretty in Pink",
  "Labyrinth",
  "The NeverEnding Story",
  "Footloose",
  "The Untouchables",
  "Crocodile Dundee",
  "48 Hrs.",
  "Midnight Run",
  "Batman",
  "Braveheart",
  "Good Will Hunting",
  "L.A. Confidential",
  "Trainspotting",
  "Philadelphia",
  "Misery",
  "Speed",
  "Ace Ventura: Pet Detective",
  "Liar Liar",
  "Mrs. Doubtfire",
  "The Mask",
  "Four Weddings and a Funeral",
  "Notting Hill",
  "A Bug's Life",
  "Toy Story 2",
  "Tarzan",
  "The Hunchback of Notre Dame",
  "Pocahontas",
  "Hercules",
  "Men in Black",
  "Twister",
  "The Fugitive",
  "As Good as It Gets",
  "Contact",
  "Austin Powers: International Man of Mystery",
  "Wayne's World",
  "Scream",
  "Malcolm X",
  "JFK",
  "Cape Fear",
  "Bram Stoker's Dracula",
  "Interview with the Vampire",
  "A Beautiful Mind",
  "Catch Me If You Can",
  "The Bourne Identity",
  "The Bourne Supremacy",
  "The Bourne Ultimatum",
  "Ocean's Eleven",
  "Kill Bill: Volume 1",
  "Kill Bill: Volume 2",
  "Eternal Sunshine of the Spotless Mind",
  "Lost in Translation",
  "Million Dollar Baby",
  "No Country for Old Men",
  "There Will Be Blood",
  "Brokeback Mountain",
  "Walk the Line",
  "Chicago",
  "Moulin Rouge!",
  "The Aviator",
  "Gangs of New York",
  "Mystic River",
  "Batman Begins",
  "District 9",
  "Inglourious Basterds",
  "Gran Torino",
  "The Curious Case of Benjamin Button",
  "Zodiac",
  "Pan's Labyrinth",
  "Blood Diamond",
  "The Last Samurai",
  "Mr. & Mrs. Smith",
  "Hitch",
  "Bruce Almighty",
  "Love Actually",
  "About a Boy",
  "Bridget Jones's Diary",
  "Lilo & Stitch",
  "The Emperor's New Groove",
  "Erin Brockovich",
  "Ray",
  "Crash",
  "Minority Report",
  "Collateral",
  "V for Vendetta",
  "Forgetting Sarah Marshall",
  "Tropic Thunder",
  "Pineapple Express",
  "Zombieland",
  "Shaun of the Dead",
  "Hot Fuzz",
  "In Bruges",
  "Snatch",
  "Lock, Stock and Two Smoking Barrels",
  "The Italian Job",
  "The Fast and the Furious",
  "The Dark Knight Rises",
  "Wonder Woman",
  "Logan",
  "Spider-Man: Into the Spider-Verse",
  "Argo",
  "12 Years a Slave",
  "Her",
  "American Hustle",
  "Birdman",
  "The Imitation Game",
  "Spotlight",
  "The Big Short",
  "Manchester by the Sea",
  "Moonlight",
  "Three Billboards Outside Ebbing, Missouri",
  "The Shape of Water",
  "Green Book",
  "Knives Out",
  "Once Upon a Time in Hollywood",
  "1917",
  "Marriage Story",
  "The Irishman",
  "Ford v Ferrari",
  "Arrival",
  "Ex Machina",
  "The Martian",
  "Dunkirk",
  "Hacksaw Ridge",
  "American Sniper",
  "Sicario",
  "Hell or High Water",
  "Drive",
  "Prisoners",
  "Gone Girl",
  "Nightcrawler",
  "The Nice Guys",
  "Baby Driver",
  "Hereditary",
  "A Star Is Born",
  "Toy Story 3",
  "How to Train Your Dragon 2",
  "The Incredibles 2",
  "Rocketman",
  "BlacKkKlansman",
  "Us",
  "Midsommar",
  "Black Swan",
  "X-Men",
  "X2: X-Men United",
  "X-Men: Days of Future Past",
  "Spider-Man 2",
  "Batman Returns",
  "Superman",
  "Ant-Man",
  "Doctor Strange",
  "Captain Marvel",
  "Mission: Impossible – Ghost Protocol",
  "Mission: Impossible – Fallout",
  "Mission: Impossible – Rogue Nation",
  "Creed",
  "Crazy Rich Asians",
  "The Town",
  "Dune",
  "No Time to Die",
  "The Batman",
  "Top Gun: Maverick",
  "Everything Everywhere All at Once",
  "Elvis",
  "Oppenheimer",
  "Barbie",
  "Killers of the Flower Moon",
  "Spider-Man: Across the Spider-Verse",
  "Saltburn",
  "Guardians of the Galaxy Vol. 3",
  "John Wick: Chapter 4",
  "Soul",
  "Onward",
  "Toy Story 4",
  "Luca",
  "Belfast",
  "Minari",
  "Jojo Rabbit",
  "Sound of Metal",
  "Promising Young Woman",
  "Nomadland",
  "CODA",
  "The Power of the Dog",
  "Past Lives",
  "Poor Things",
  "Drive My Car",
  "A Separation",
  "Wild Tales",
  "Roma",
  "Shoplifters",
  "Portrait of a Lady on Fire",
  "Let the Right One In",
];

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function searchMovie(title) {
  const url = `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=${encodeURIComponent(title)}&language=en-US&page=1`;
  const res = await fetch(url);
  const data = await res.json();
  if (!data.results || data.results.length === 0) return null;
  const movie = data.results[0];
  return {
    id: String(movie.id),
    title: movie.title,
    poster_path: movie.poster_path || null,
    release_date: movie.release_date || null,
    overview: movie.overview || null,
  };
}

async function main() {
  const results = [];
  const failed = [];

  console.log(`Searching TMDB for ${MOVIE_TITLES.length} movies...`);

  for (let i = 0; i < MOVIE_TITLES.length; i++) {
    const title = MOVIE_TITLES[i];
    process.stdout.write(`[${i + 1}/${MOVIE_TITLES.length}] ${title}... `);

    try {
      const movie = await searchMovie(title);
      if (movie) {
        results.push(movie);
        console.log(`✓ ${movie.title} (${movie.release_date?.slice(0, 4)})`);
      } else {
        failed.push(title);
        console.log("✗ not found");
      }
    } catch (err) {
      failed.push(title);
      console.log(`✗ error: ${err.message}`);
    }

    await sleep(DELAY_MS);
  }

  // Write output
  const outputDir = path.join(__dirname, "..", "src", "data");
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const outputPath = path.join(outputDir, "defaultMovies.json");
  fs.writeFileSync(outputPath, JSON.stringify(results, null, 2));

  console.log(
    `\n✓ Saved ${results.length} movies to src/data/defaultMovies.json`,
  );
  if (failed.length > 0) {
    console.log(`✗ ${failed.length} not found: ${failed.join(", ")}`);
  }
}

main();
